name: fairlisa
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python=3.9
  - pip=22.2.2
  - sfe1ed40::recommenders
  - pip:
      - tensorflow
      - torch
      - pandas==1.5.3
      - numpy
      - scikit-learn
      - tqdm
      - openpyxl
